package recipesearch;

import java.awt.CardLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import se.chalmers.ait.dat215.lab2.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class RecipeSearchView extends javax.swing.JFrame implements ActionListener {
    
    private RecipeController recCon = new RecipeController();
    private ArrayList<JButton> reciButtons = new ArrayList<JButton>();
    private String kitchenItem;
    private String ingredientItem;
    private String difficultyItem;
    private int maxTime;
    private int maxPrice;
    private Recipe currentRecipe;
    private int recipeNumber;
    private CardLayout cl;
    private final static String newline = "\n";
    
    /**
     * Creates new form ExampleApplicationView
     */
    public RecipeSearchView() {
        initComponents();
        cl = (CardLayout)recipeTopPanel.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        searchPanel = new javax.swing.JPanel();
        kitchenLabel = new javax.swing.JLabel();
        kitchenList = new javax.swing.JComboBox();
        mainIngredientLabel = new javax.swing.JLabel();
        mainIngredientList = new javax.swing.JComboBox();
        difficultyLabel = new javax.swing.JLabel();
        difficultyList = new javax.swing.JComboBox();
        priceLabel = new javax.swing.JLabel();
        priceSpinner = new javax.swing.JSpinner();
        timeLabel = new javax.swing.JLabel();
        timeSpinner = new javax.swing.JSpinner();
        searchButton = new javax.swing.JButton();
        recipeTopPanel = new javax.swing.JPanel();
        searchHitsPane = new javax.swing.JScrollPane();
        searchHitsPanel = new javax.swing.JPanel();
        detailedPane = new javax.swing.JScrollPane();
        detailedPanel = new javax.swing.JPanel();
        returnButton = new javax.swing.JButton();
        iconLabel = new javax.swing.JLabel();
        recipeNameLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        descriptionTextAreaPane = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        kitchenLabel2 = new javax.swing.JLabel();
        kitchenTextField = new javax.swing.JTextField();
        difficultyLabel2 = new javax.swing.JLabel();
        difficultyTextField = new javax.swing.JTextField();
        priceLabel2 = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        timeLabel2 = new javax.swing.JLabel();
        timeTextField = new javax.swing.JTextField();
        portionsLabel = new javax.swing.JLabel();
        portionsTextField = new javax.swing.JTextField();
        mainIngredientLabel2 = new javax.swing.JLabel();
        mainIngredientTextField = new javax.swing.JTextField();
        ingredientsLabel = new javax.swing.JLabel();
        ingredientsTextAreaPane = new javax.swing.JScrollPane();
        ingredientsTextArea = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("recipesearch/resources/RecipeSearch"); // NOI18N
        setTitle(bundle.getString("Application.title")); // NOI18N
        setName("applicationFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 800));

        splitPane.setEnabled(false);

        kitchenLabel.setText("Kök:");

        kitchenList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Sverige", "Grekland", "Indien", "Asien", "Afrika", "Frankrike" }));
        kitchenList.setToolTipText("Ställ in maträttens ursprungsland");
        kitchenList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitchenListActionPerformed(evt);
            }
        });

        mainIngredientLabel.setText("Huvudingrediens:");

        mainIngredientList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Kött", "Fisk", "Kyckling", "Vegetarisk" }));
        mainIngredientList.setToolTipText("Ställ in maträttens huvudingrediens");

        difficultyLabel.setText("Svårighetsgrad:");

        difficultyList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Lätt", "Mellan", "Svår" }));
        difficultyList.setToolTipText("Ställ in maträttens svårighetsgrad");

        priceLabel.setText("Maxpris:");

        priceSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        priceSpinner.setToolTipText("Ställ in maximala priset för maträtten");

        timeLabel.setText("Maxtid:");

        timeSpinner.setModel(new javax.swing.SpinnerNumberModel(10, 10, 150, 10));
        timeSpinner.setToolTipText("Ställ in maximala tiden maträtten ska ta att laga");

        searchButton.setText("Sök");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(kitchenList, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(priceLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kitchenLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(difficultyLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainIngredientList, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainIngredientLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(difficultyList, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(priceSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kitchenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kitchenList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainIngredientLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainIngredientList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(difficultyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(difficultyList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchButton)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(searchPanel);

        recipeTopPanel.setPreferredSize(new java.awt.Dimension(500, 500));
        recipeTopPanel.setLayout(new java.awt.CardLayout());

        searchHitsPanel.setAutoscrolls(true);
        searchHitsPanel.setLayout(new java.awt.GridLayout(0, 1));
        searchHitsPane.setViewportView(searchHitsPanel);

        recipeTopPanel.add(searchHitsPane, "searchHitsPanel");

        detailedPane.setPreferredSize(new java.awt.Dimension(200, 200));

        detailedPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        returnButton.setText("<-- Tillbaka");
        returnButton.setToolTipText("Gå tillbaka till sökresultat");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        recipeNameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        recipeNameLabel.setText("Recept");

        descriptionLabel.setText("Beskrivning:");

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setRows(5);
        descriptionTextAreaPane.setViewportView(descriptionTextArea);

        kitchenLabel2.setText("Kök:");

        kitchenTextField.setEditable(false);
        kitchenTextField.setText("jTextField1");

        difficultyLabel2.setText("Svårighetsgrad:");

        difficultyTextField.setEditable(false);
        difficultyTextField.setText("jTextField1");

        priceLabel2.setText("Pris:");

        priceTextField.setEditable(false);
        priceTextField.setText("jTextField1");

        timeLabel2.setText("Tid:");

        timeTextField.setEditable(false);
        timeTextField.setText("jTextField1");

        portionsLabel.setText("Portioner:");

        portionsTextField.setEditable(false);
        portionsTextField.setText("jTextField1");

        mainIngredientLabel2.setText("Huvudingrediens:");

        mainIngredientTextField.setEditable(false);
        mainIngredientTextField.setText("jTextField1");

        ingredientsLabel.setText("Ingredienser:");

        ingredientsTextArea.setEditable(false);
        ingredientsTextArea.setColumns(20);
        ingredientsTextArea.setRows(5);
        ingredientsTextAreaPane.setViewportView(ingredientsTextArea);

        javax.swing.GroupLayout detailedPanelLayout = new javax.swing.GroupLayout(detailedPanel);
        detailedPanel.setLayout(detailedPanelLayout);
        detailedPanelLayout.setHorizontalGroup(
            detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailedPanelLayout.createSequentialGroup()
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnButton)
                    .addGroup(detailedPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ingredientsLabel)
                            .addComponent(descriptionLabel)
                            .addComponent(ingredientsTextAreaPane, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                            .addComponent(descriptionTextAreaPane))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(detailedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailedPanelLayout.createSequentialGroup()
                        .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recipeNameLabel))
                    .addGroup(detailedPanelLayout.createSequentialGroup()
                        .addComponent(portionsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(portionsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detailedPanelLayout.createSequentialGroup()
                        .addComponent(difficultyLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(difficultyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detailedPanelLayout.createSequentialGroup()
                        .addComponent(mainIngredientLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainIngredientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detailedPanelLayout.createSequentialGroup()
                        .addComponent(kitchenLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kitchenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detailedPanelLayout.createSequentialGroup()
                        .addComponent(priceLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detailedPanelLayout.createSequentialGroup()
                        .addComponent(timeLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(488, Short.MAX_VALUE))
        );
        detailedPanelLayout.setVerticalGroup(
            detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailedPanelLayout.createSequentialGroup()
                .addComponent(returnButton)
                .addGap(18, 18, 18)
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recipeNameLabel))
                .addGap(23, 23, 23)
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kitchenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kitchenLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainIngredientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainIngredientLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(difficultyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(difficultyLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel2)
                    .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portionsLabel)
                    .addComponent(portionsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionTextAreaPane, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ingredientsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingredientsTextAreaPane, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        detailedPane.setViewportView(detailedPanel);

        recipeTopPanel.add(detailedPane, "detailedPanel");

        splitPane.setRightComponent(recipeTopPanel);

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("recipesearch/resources/RecipeSearchView"); // NOI18N
        fileMenu.setText(bundle1.getString("fileMenu.text")); // NOI18N

        exitMenuItem.setText(bundle1.getString("exitApplicationMenuItem.text")); // NOI18N
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(bundle1.getString("helpMenu.text")); // NOI18N

        aboutMenuItem.setText(bundle1.getString("aboutMenuItem.text")); // NOI18N
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        new RecipeSearchAboutBox(this).setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed
    
    private void kitchenListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitchenListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kitchenListActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        cl.show(recipeTopPanel, "searchHitsPanel");
        
        maxTime = (int)timeSpinner.getValue();
        maxPrice = (int)priceSpinner.getValue();
        
        if(kitchenList.getSelectedItem().toString().equals("")){
            kitchenItem = null;
        }else{
            kitchenItem = kitchenList.getSelectedItem().toString();
        }
        
        if(mainIngredientList.getSelectedItem().toString().equals("")){
            ingredientItem = null;
        }else{
            ingredientItem = mainIngredientList.getSelectedItem().toString();
        }
        
        if(difficultyList.getSelectedItem().toString().equals("")){
            difficultyItem = null;
        }else{
            difficultyItem = difficultyList.getSelectedItem().toString();
        }
        
        recCon.doSearch(difficultyItem, maxTime, kitchenItem, maxPrice, ingredientItem);
        reciButtons.clear();
        searchHitsPanel.removeAll();
        
        for(int i = 0; i< recCon.recipes.size(); i++){
            if(recCon.recipes.get(i).getMatch() > 49){
                reciButtons.add(i, (new JButton(recCon.recipes.get(i).getName() + " " + recCon.recipes.get(i).getCuisine() + " " + recCon.recipes.get(i).getMainIngredient() + " " + recCon.recipes.get(i).getDifficulty() + " " + recCon.recipes.get(i).getPrice() + " " + recCon.recipes.get(i).getTime() + " " + recCon.recipes.get(i).getMatch())));
                reciButtons.get(i).setIcon(recCon.recipes.get(i).getImage(100, 100));
                reciButtons.get(i).setActionCommand("" + i);
                searchHitsPanel.add(reciButtons.get(i));
                reciButtons.get(i).addActionListener(this);
            }
        }
        
        revalidate();
        repaint();
    }//GEN-LAST:event_searchButtonActionPerformed

    @Override
    public void actionPerformed(ActionEvent e) {
        JButton tempButton = (JButton)e.getSource();
        recipeNumber = Integer.parseInt(tempButton.getActionCommand());
        currentRecipe = recCon.recipes.get(recipeNumber);
        
        iconLabel.setIcon(currentRecipe.getImage(iconLabel.getSize()));
        recipeNameLabel.setText(currentRecipe.getName());
        kitchenTextField.setText(currentRecipe.getCuisine());
        mainIngredientTextField.setText(currentRecipe.getMainIngredient());
        difficultyTextField.setText(currentRecipe.getDifficulty());
        timeTextField.setText( currentRecipe.getTime() + " minuter");
        priceTextField.setText("" + currentRecipe.getPrice() + " kr");
        timeTextField.setText("" + currentRecipe.getServings() + " minuter");
        portionsTextField.setText("" + currentRecipe.getServings());
        
        descriptionTextArea.setText(currentRecipe.getDescription());
        ingredientsTextArea.setText("");
        
        for(int i = 0; i < currentRecipe.getIngredients().size(); i++){
            ingredientsTextArea.append(currentRecipe.getIngredients().get(i) + newline);
        }
        
        
        
        cl.show(recipeTopPanel, "detailedPanel");
    }
    
    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        cl.show(recipeTopPanel, "searchHitsPanel");
    }//GEN-LAST:event_returnButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JScrollPane descriptionTextAreaPane;
    private javax.swing.JScrollPane detailedPane;
    private javax.swing.JPanel detailedPanel;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JLabel difficultyLabel2;
    private javax.swing.JComboBox difficultyList;
    private javax.swing.JTextField difficultyTextField;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel ingredientsLabel;
    private javax.swing.JTextArea ingredientsTextArea;
    private javax.swing.JScrollPane ingredientsTextAreaPane;
    private javax.swing.JLabel kitchenLabel;
    private javax.swing.JLabel kitchenLabel2;
    private javax.swing.JComboBox kitchenList;
    private javax.swing.JTextField kitchenTextField;
    private javax.swing.JLabel mainIngredientLabel;
    private javax.swing.JLabel mainIngredientLabel2;
    private javax.swing.JComboBox mainIngredientList;
    private javax.swing.JTextField mainIngredientTextField;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel portionsLabel;
    private javax.swing.JTextField portionsTextField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceLabel2;
    private javax.swing.JSpinner priceSpinner;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel recipeNameLabel;
    private javax.swing.JPanel recipeTopPanel;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JScrollPane searchHitsPane;
    private javax.swing.JPanel searchHitsPanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel timeLabel2;
    private javax.swing.JSpinner timeSpinner;
    private javax.swing.JTextField timeTextField;
    // End of variables declaration//GEN-END:variables

}