package recipesearch;

import java.awt.CardLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import se.chalmers.ait.dat215.lab2.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class RecipeSearchView extends javax.swing.JFrame implements ActionListener {
    
    private RecipeController recCon = new RecipeController();
    private ArrayList<JButton> reciButtons = new ArrayList<JButton>();
    private String kitchenItem;
    private String ingredientItem;
    private String difficultyItem;
    private int maxTime;
    private int maxPrice;
    private Recipe currentRecipe;
    private int recipeNumber;
    private CardLayout cl;
    private final static String newline = "\n";
    
    /**
     * Creates new form ExampleApplicationView
     */
    public RecipeSearchView() {
        initComponents();
        cl = (CardLayout)recipeTopPanel.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        searchPanel = new javax.swing.JPanel();
        kitchenLabel = new javax.swing.JLabel();
        kitchenList = new javax.swing.JComboBox();
        mainIngredientLabel = new javax.swing.JLabel();
        mainIngredientList = new javax.swing.JComboBox();
        difficultyLabel = new javax.swing.JLabel();
        difficultyList = new javax.swing.JComboBox();
        priceLabel = new javax.swing.JLabel();
        priceSpinner = new javax.swing.JSpinner();
        timeLabel = new javax.swing.JLabel();
        timeSpinner = new javax.swing.JSpinner();
        searchButton = new javax.swing.JButton();
        recipeTopPanel = new javax.swing.JPanel();
        searchHitsPane = new javax.swing.JScrollPane();
        searchHitsPanel = new javax.swing.JPanel();
        awaitingSearchLabel = new javax.swing.JLabel();
        detailedPane = new javax.swing.JScrollPane();
        detailedPanel = new javax.swing.JPanel();
        returnButton = new javax.swing.JButton();
        iconLabel = new javax.swing.JLabel();
        recipeNameLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        descriptionTextAreaPane = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        ingredientsLabel = new javax.swing.JLabel();
        ingredientsTextAreaPane = new javax.swing.JScrollPane();
        ingredientsTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        kitchenLabel2 = new javax.swing.JLabel();
        mainIngredientLabel2 = new javax.swing.JLabel();
        portionsLabel = new javax.swing.JLabel();
        timeLabel2 = new javax.swing.JLabel();
        priceLabel2 = new javax.swing.JLabel();
        difficultyLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        writableKitchenLabel = new javax.swing.JLabel();
        writableIngredientLabel = new javax.swing.JLabel();
        writablePortionLabel = new javax.swing.JLabel();
        writableDifficultyLabel = new javax.swing.JLabel();
        writablePriceLabel = new javax.swing.JLabel();
        writableTimeLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("recipesearch/resources/RecipeSearch"); // NOI18N
        setTitle(bundle.getString("Application.title")); // NOI18N
        setName("applicationFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 800));

        splitPane.setEnabled(false);

        kitchenLabel.setText("Kök:");

        kitchenList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Sverige", "Grekland", "Indien", "Asien", "Afrika", "Frankrike" }));
        kitchenList.setToolTipText("Ställ in maträttens ursprungsland");
        kitchenList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitchenListActionPerformed(evt);
            }
        });

        mainIngredientLabel.setText("Huvudingrediens:");

        mainIngredientList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Kött", "Fisk", "Kyckling", "Vegetarisk" }));
        mainIngredientList.setToolTipText("Ställ in maträttens huvudingrediens");

        difficultyLabel.setText("Svårighetsgrad:");

        difficultyList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Lätt", "Mellan", "Svår" }));
        difficultyList.setToolTipText("Ställ in maträttens svårighetsgrad");

        priceLabel.setText("Maxpris:");

        priceSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        priceSpinner.setToolTipText("Ställ in maximala priset för maträtten");

        timeLabel.setText("Maxtid:");

        timeSpinner.setModel(new javax.swing.SpinnerNumberModel(10, 10, 150, 10));
        timeSpinner.setToolTipText("Ställ in maximala tiden maträtten ska ta att laga");

        searchButton.setText("Sök");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(kitchenList, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(priceLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kitchenLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(difficultyLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainIngredientList, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainIngredientLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(difficultyList, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(priceSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kitchenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kitchenList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainIngredientLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainIngredientList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(difficultyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(difficultyList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchButton)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(searchPanel);

        recipeTopPanel.setPreferredSize(new java.awt.Dimension(500, 500));
        recipeTopPanel.setLayout(new java.awt.CardLayout());

        searchHitsPanel.setAutoscrolls(true);
        searchHitsPanel.setLayout(new java.awt.GridLayout(0, 1));

        awaitingSearchLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        awaitingSearchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        awaitingSearchLabel.setText("Sök på recept genom att välja sökkriterier och klicka \"sök\".");
        searchHitsPanel.add(awaitingSearchLabel);

        searchHitsPane.setViewportView(searchHitsPanel);

        recipeTopPanel.add(searchHitsPane, "searchHitsPanel");

        detailedPane.setPreferredSize(new java.awt.Dimension(200, 200));

        detailedPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        returnButton.setText("<-- Tillbaka");
        returnButton.setToolTipText("Gå tillbaka till sökresultat");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        recipeNameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        recipeNameLabel.setText("Recept");

        descriptionLabel.setText("Beskrivning:");

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setRows(5);
        descriptionTextAreaPane.setViewportView(descriptionTextArea);

        ingredientsLabel.setText("Ingredienser:");

        ingredientsTextArea.setEditable(false);
        ingredientsTextArea.setColumns(20);
        ingredientsTextArea.setRows(5);
        ingredientsTextAreaPane.setViewportView(ingredientsTextArea);

        kitchenLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        kitchenLabel2.setText("Kök:");

        mainIngredientLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        mainIngredientLabel2.setText("Huvudingrediens:");

        portionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        portionsLabel.setText("Portioner:");

        timeLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        timeLabel2.setText("Tid:");

        priceLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        priceLabel2.setText("Pris:");

        difficultyLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        difficultyLabel2.setText("Svårighetsgrad:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        writableKitchenLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        writableKitchenLabel.setText("kitchen...");

        writableIngredientLabel.setText("ingredient...");

        writablePortionLabel.setText("portions...");

        writableDifficultyLabel.setText("difficulty...");

        writablePriceLabel.setText("price...");

        writableTimeLabel.setText("time...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainIngredientLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kitchenLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(portionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(difficultyLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(priceLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timeLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(writableIngredientLabel)
                    .addComponent(writableKitchenLabel)
                    .addComponent(writablePortionLabel)
                    .addComponent(writableDifficultyLabel)
                    .addComponent(writablePriceLabel)
                    .addComponent(writableTimeLabel))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kitchenLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainIngredientLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(portionsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(difficultyLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(writableKitchenLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(writableIngredientLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(writablePortionLabel)
                        .addGap(18, 18, 18)
                        .addComponent(writableDifficultyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(writablePriceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(writableTimeLabel)))
                .addContainerGap())
        );

        javax.swing.GroupLayout detailedPanelLayout = new javax.swing.GroupLayout(detailedPanel);
        detailedPanel.setLayout(detailedPanelLayout);
        detailedPanelLayout.setHorizontalGroup(
            detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailedPanelLayout.createSequentialGroup()
                .addComponent(returnButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(detailedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLabel)
                    .addGroup(detailedPanelLayout.createSequentialGroup()
                        .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recipeNameLabel))
                    .addGroup(detailedPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(descriptionTextAreaPane, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientsTextAreaPane, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientsLabel))
                .addContainerGap(318, Short.MAX_VALUE))
        );
        detailedPanelLayout.setVerticalGroup(
            detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailedPanelLayout.createSequentialGroup()
                .addComponent(returnButton)
                .addGap(18, 18, 18)
                .addGroup(detailedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recipeNameLabel))
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingredientsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(ingredientsTextAreaPane, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionTextAreaPane, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        detailedPane.setViewportView(detailedPanel);

        recipeTopPanel.add(detailedPane, "detailedPanel");

        splitPane.setRightComponent(recipeTopPanel);

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("recipesearch/resources/RecipeSearchView"); // NOI18N
        fileMenu.setText(bundle1.getString("fileMenu.text")); // NOI18N

        exitMenuItem.setText(bundle1.getString("exitApplicationMenuItem.text")); // NOI18N
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(bundle1.getString("helpMenu.text")); // NOI18N

        aboutMenuItem.setText(bundle1.getString("aboutMenuItem.text")); // NOI18N
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        new RecipeSearchAboutBox(this).setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed
    
    private void kitchenListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitchenListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kitchenListActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        cl.show(recipeTopPanel, "searchHitsPanel");
        
        maxTime = (int)timeSpinner.getValue();
        maxPrice = (int)priceSpinner.getValue();
        
        if(kitchenList.getSelectedItem().toString().equals("")){
            kitchenItem = null;
        }else{
            kitchenItem = kitchenList.getSelectedItem().toString();
        }
        
        if(mainIngredientList.getSelectedItem().toString().equals("")){
            ingredientItem = null;
        }else{
            ingredientItem = mainIngredientList.getSelectedItem().toString();
        }
        
        if(difficultyList.getSelectedItem().toString().equals("")){
            difficultyItem = null;
        }else{
            difficultyItem = difficultyList.getSelectedItem().toString();
        }
        
        recCon.doSearch(difficultyItem, maxTime, kitchenItem, maxPrice, ingredientItem);
        reciButtons.clear();
        searchHitsPanel.removeAll();
        
        for(int i = 0; i< recCon.recipes.size(); i++){
            if(recCon.recipes.get(i).getMatch() > 49){
                reciButtons.add(i, (new JButton("<html><body>" + recCon.recipes.get(i).getName() + 
                        "<br />" + recCon.recipes.get(i).getCuisine() + " " + 
                        recCon.recipes.get(i).getMainIngredient() + " " + 
                        recCon.recipes.get(i).getDifficulty() + " " + 
                        "<br />" +
                        recCon.recipes.get(i).getPrice() + " kr " + 
                        recCon.recipes.get(i).getTime() + " minuter " + 
                        recCon.recipes.get(i).getMatch() + "% matchning" + "</body></html>"
                        )));
                
                //("<html><body>line 1 <br /> line 2</body></html>")
                        
                reciButtons.get(i).setIcon(recCon.recipes.get(i).getImage(100, 100));
                reciButtons.get(i).setHorizontalAlignment(SwingConstants.LEFT);
                reciButtons.get(i).setActionCommand(Integer.toString(i));
                searchHitsPanel.add(reciButtons.get(i));
                reciButtons.get(i).addActionListener(this);
            }
        }
        
        revalidate();
        repaint();
    }//GEN-LAST:event_searchButtonActionPerformed

    @Override
    public void actionPerformed(ActionEvent e) {
        JButton tempButton = (JButton)e.getSource();
        recipeNumber = Integer.parseInt(tempButton.getActionCommand());
        currentRecipe = recCon.recipes.get(recipeNumber);
        
        iconLabel.setIcon(currentRecipe.getImage(iconLabel.getSize()));
        recipeNameLabel.setText(currentRecipe.getName());
        writableKitchenLabel.setText(currentRecipe.getCuisine());
        
        writableIngredientLabel.setText(currentRecipe.getMainIngredient());
        
        writableDifficultyLabel.setText(currentRecipe.getDifficulty());
       
        writableTimeLabel.setText( currentRecipe.getTime() + " minuter");
        
        writablePriceLabel.setText(currentRecipe.getPrice() + " kr");
        
        
        writablePortionLabel.setText(Integer.toString(currentRecipe.getServings()));
        
        descriptionTextArea.setText(currentRecipe.getDescription());
        ingredientsTextArea.setText("");
        
        for(int i = 0; i < currentRecipe.getIngredients().size(); i++){
            ingredientsTextArea.append(currentRecipe.getIngredients().get(i) + newline);
        }
        
        
        
        cl.show(recipeTopPanel, "detailedPanel");
    }
    
    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        cl.show(recipeTopPanel, "searchHitsPanel");
    }//GEN-LAST:event_returnButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JLabel awaitingSearchLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JScrollPane descriptionTextAreaPane;
    private javax.swing.JScrollPane detailedPane;
    private javax.swing.JPanel detailedPanel;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JLabel difficultyLabel2;
    private javax.swing.JComboBox difficultyList;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel ingredientsLabel;
    private javax.swing.JTextArea ingredientsTextArea;
    private javax.swing.JScrollPane ingredientsTextAreaPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel kitchenLabel;
    private javax.swing.JLabel kitchenLabel2;
    private javax.swing.JComboBox kitchenList;
    private javax.swing.JLabel mainIngredientLabel;
    private javax.swing.JLabel mainIngredientLabel2;
    private javax.swing.JComboBox mainIngredientList;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel portionsLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceLabel2;
    private javax.swing.JSpinner priceSpinner;
    private javax.swing.JLabel recipeNameLabel;
    private javax.swing.JPanel recipeTopPanel;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JScrollPane searchHitsPane;
    private javax.swing.JPanel searchHitsPanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel timeLabel2;
    private javax.swing.JSpinner timeSpinner;
    private javax.swing.JLabel writableDifficultyLabel;
    private javax.swing.JLabel writableIngredientLabel;
    private javax.swing.JLabel writableKitchenLabel;
    private javax.swing.JLabel writablePortionLabel;
    private javax.swing.JLabel writablePriceLabel;
    private javax.swing.JLabel writableTimeLabel;
    // End of variables declaration//GEN-END:variables

}